name: Publish Docker Image

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Commit
        run: echo -n "$(git rev-parse --short HEAD)" > constants/git_commit.txt

      - name: Set Version
        run: echo -n "$GITHUB_REF_NAME" > constants/version.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/imgu2:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/imgu2:${{ github.ref_name }}
